### ISSUE TITLE
Failure to find com.sonarsource.security:sonar-security-java-frontend-plugin:jar:7.5.0.1971

### ISSUE THREAD

**Issue by switchover** [SonarSource/source-graph-viewer#45]
Hello

I can't build with maven central repository..
```
Error message : Failure to find com.sonarsource.security:sonar-security-java-frontend-plugin:jar:7.5.0.1971
```
Do I need to specify another repository?

Thank you

**Comment by m-g-sonar** [comment]
Hello,

Thanks for the feedback. Indeed, we forgot that when adding the latest feature, we had to rely on a private artifact. This artifact is not available publicly:
* first because development is not over on this version yet,
* And I'm not sure it's going to be available in maven central anyway after the release (I need to check this with our builder team).

If you want to be able to build/use the viewer, the best workaround for the time being would be to revert to https://github.com/SonarSource/source-graph-viewer/commit/621adad319e58c33c860fdbe6ba0d6e36b715642 (removing last graph that we added for our internal development). I'm going to work on it to find a more elegant way.

An couple questions for you @switchover:
* Did you used the viewer already or is it your first try?
* For what purpose are you using it, planning to use it?

Cheers,
Michael

**Comment by switchover** [comment]
Thank you for your kind reply.

And I am trying for the first time and looking for a sonarqube plugin that draws CFGs in my company.

Thank you so much.

**Comment by m-g-sonar** [comment]
Okay, thanks for the precision.
If you need to draw CFGs for your Java code (for other languages, almost nothing have been made yet),  I would encourage you to **not** use this tool.

Since release 5.9, you can access the CFG of any method in the native API of the SonarJava analyzer: [SonarSource/sonar-java/5.9.1.16423/.../java/api/tree/MethodTree.java#L106](https://github.com/SonarSource/sonar-java/blob/5.9.1.16423/java-frontend/src/main/java/org/sonar/plugins/java/api/tree/MethodTree.java#L106)

Knowing that, I would consequently try to design a custom plugin and draw my own CFGs (following the tutorial on how to write rules my help: [Writing Custom Java Rules](https://docs.sonarqube.org/display/PLUG/Writing+Custom+Java+Rules+101))

Now, after discussing with our builder team, it seems that we are going to move the project into a c**losed source repository**. The tool was initially made public, because we didn't know really what would be its scope, or how/if the community could use it. It's also a quite experimental stool, which is hugely impacted by evolution of our analyzers. We now want to expand it functionalities, but with a focus on our close source projects.
